#!/usr/bin/python3 
# Name: 		Calibre News Get
# Author:		Dreammer12138
# Github:		https://github.com/dreammer12138
# Description:	Settings
# -*- coding: utf-8 -*-

import os
import sys,getopt
import json
import re
import configset

opts, args = getopt.getopt(sys.argv[1:], "hv", [
	"news-add=",
	"news-remove=",
	"news-custom-add=",
	"news-custom-remove=",
	"news-list",
	"news-custom-list",
	"update-conf",
	"set-update-time=",
	"set-update-interval=",
	"version",
	"help"])

_path = sys.path[0]

for opt, val in opts :
	if opt in ("--help", "-h") :
		print("""
-h, --help\t\t\t\t帮助
-v, --version\t\t\t\t版本信息
--news-add\t\t\t\t添加新闻源 --news-add "Global Times"
--news-remove\t\t\t\t移除新闻源 --news-remove "Global Times"
--news-list\t\t\t\t列出新闻源 --news-list
--news-custom-add\t\t\t添加自定义新闻源 --news-custom-add 明日方舟=https://rsshub.app/arknights/news
--news-custom-remove\t\t\t移除自定义新闻源 --news-custom-remove 明日方舟
--news-custom-list\t\t\t列出自定义新闻源 --news-custom-list
--set-update-time\t\t\t设置更新时间 --set-update-time 6:00
--set-update-interval\t\t\t设置更新间隔[day/week/month] --set-update-interval day
			""")

	if opt in ("--version", "-v") :
		version = configset.readconfig("{}/config.json".format(_path))['version']
		print("Calibre News autoget version {}".format(version))
		print("For more information, please visit https://github.com/dreammer12138/Calibre-News-autoget")

	if opt in ("--news-add") :
		add_news = val
		config = configset.readconfig("{}/config.json".format(_path))

		config['news'].append(add_news)
		configset.writeconfig("{}/config.json".format(_path), config)

		print("OK")

	if opt in ("--news-remove") :
		remove_news = val
		print(remove_news)
		config = configset.readconfig("{}/config.json".format(_path))

		for n in config['news'] :
			if n == remove_news :
				config['news'].remove(n)

		configset.writeconfig("{}/config.json".format(_path), config)

		print("OK")

	if opt in ("--news-custom-add") :
		rss = val.split("=")[0]
		rss_url = val.split("=")[1]

		config = configset.readconfig("{}/recipes/recipe.json".format(_path))

		exist = False

		for newslist in config :
			if rss in newslist :
				print("RSS已存在")
				exist = True
		if exist == False :		
			config.append([rss, rss_url])
			configset.writeconfig("{}/recipes/recipe.json".format(_path), config)
			configset.add_recipe("{}/recipes/{}.recipe".format(_path, rss), "{}/recipes/recipe.json".format(_path), rss, rss_url)

	if opt in ("--news-custom-remove") :
		news = val
		config = configset.readconfig("{}/recipes/recipe.json".format(_path))
		exist = 0

		for newslist in config :
			if news in newslist :
				exist = True

		if exist == False :
			print("RSS不存在")
		elif exist == True :
			for newslist in config :
				if news in newslist :
					config.remove(newslist)

		configset.writeconfig("{}/recipes/recipe.json".format(_path), config)

	if opt in ("--news-custom-list") :
		config = configset.readconfig("{}/recipes/recipe.json".format(_path))
		for newslist in config :
			print(newslist[0])

	if opt in ("--news-list") :
		config = configset.readconfig("{}/config.json".format(_path))

		for n in config['news'] :
			print(n)

		print("OK")

	if opt in ("--update-conf") :
		config = configset.readconfig("{}/config.json".format(_path))

		for u in config['update'] :
			print("{}\t{}".format(u, config['update'][u]))

		print("OK")

	if opt in ("--set-update-time") :
		time = val
		config = configset.readconfig("{}/config.json".format(_path))

		config['update']['time'] = time
		configset.writeconfig("{}/config.json".format(_path), config)

		print("OK")	
	
	if opt in ("--set-update-interval") :
		interval = val
		interval_val = 0
		if interval == "day" :
			interval_val = 0
		elif interval == "week" :
			interval_val = 6
		elif interval == "month" :
			interval_val = 29

		config = configset.readconfig("{}/config.json".format(_path))

		config['update']['interval'] = interval_val
		configset.writeconfig("{}/config.json".format(_path), config)	
		print("OK")